name: 'AI-Michael Review'
description: 'Reviews your PRs a bit'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node18'
  main: 'index.mjs'